/**
 * Audit-readiness report PDF — the native-download twin of
 * app/app/reports/[id]/print. Content parity with the print view plus the
 * workforce / task indicators the on-screen report shows.
 */
import { PdfDoc } from "./doc";

export interface ReportPdfInput {
  id: string;
  report_type: string;
  framework: string | null;
  generated_at: string;
  ai_executive_summary: string | null;
  snapshot: {
    practice_name?: string;
    readiness?: Array<{ framework_code: string; weighted_pct: number; satisfied: number; total: number }>;
    critical_open?: number;
    recent_drift_alerts_30d?: number;
    vendors_missing_baa?: number;
    tasks_open?: number;
    tasks_overdue?: number;
    tasks_critical?: number;
    training_current?: number;
    training_expired?: number;
    screenings_total?: number;
    screenings_blocked?: number;
    screenings_stale?: number;
  } | null;
}

export async function buildReportPdf(report: ReportPdfInput): Promise<Uint8Array> {
  const doc = await PdfDoc.create();
  const snap = report.snapshot ?? {};
  const generatedAt = new Date(report.generated_at).toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
    timeZone: "UTC",
  });

  doc.brandHeader([
    `${report.report_type.replace(/_/g, " ").toUpperCase()}${report.framework ? ` - ${report.framework}` : ""}`,
    `${generatedAt} UTC`,
  ]);

  doc.title(snap.practice_name ?? "Compliance report");
  doc.subtitle("Audit readiness snapshot & executive summary");

  if (snap.readiness && snap.readiness.length > 0) {
    doc.sectionTitle("Per-framework posture");
    doc.table(
      [
        { header: "Framework", flex: 3 },
        { header: "Readiness", flex: 1, align: "right" },
        { header: "Satisfied", flex: 1, align: "right" },
        { header: "Total", flex: 1, align: "right" },
      ],
      snap.readiness.map((r) => [
        r.framework_code,
        `${Math.round(Number(r.weighted_pct) || 0)}%`,
        String(r.satisfied),
        String(r.total),
      ])
    );
  }

  doc.sectionTitle("Key indicators");
  doc.table(
    [
      { header: "Indicator", flex: 4 },
      { header: "Value", flex: 1, align: "right" },
    ],
    [
      ["Critical controls open", String(snap.critical_open ?? 0)],
      ["Drift alerts (last 30 days)", String(snap.recent_drift_alerts_30d ?? 0)],
      ["Vendors missing a current BAA", String(snap.vendors_missing_baa ?? 0)],
      ["Remediation tasks open", String(snap.tasks_open ?? 0)],
      ["Remediation tasks overdue", String(snap.tasks_overdue ?? 0)],
      ["Workforce training current", String(snap.training_current ?? 0)],
      ["Workforce training expired", String(snap.training_expired ?? 0)],
      ["Exclusion screenings on file", String(snap.screenings_total ?? 0)],
      ["Exclusion screenings blocked", String(snap.screenings_blocked ?? 0)],
    ]
  );

  if (report.ai_executive_summary) {
    doc.sectionTitle("Executive summary");
    doc.paragraph(report.ai_executive_summary, { size: 11, lineGap: 1.55 });
  }

  return doc.finalize([
    "Generated by Fortify. This document does not contain Protected Health Information (45 CFR 160.103). Fortify operates on compliance metadata only.",
    `Report ID: ${report.id}`,
  ]);
}
