import { notFound } from "next/navigation";
import { createAuthedServerClient } from "@/lib/supabase/server-auth";
import { getAppSession, assertActive } from "@/lib/auth/session";

export const dynamic = "force-dynamic";

interface ReportRow {
  id: string;
  report_type: string;
  framework: string | null;
  generated_at: string;
  snapshot: {
    practice_name?: string;
    readiness?: Array<{ framework_code: string; weighted_pct: number; satisfied: number; total: number }>;
    critical_open?: number;
    recent_drift_alerts_30d?: number;
    vendors_missing_baa?: number;
  } | null;
  ai_executive_summary: string | null;
}

/**
 * Print-optimized report view.
 *
 * Designed for the browser's native "Print → Save as PDF". The @page CSS
 * gives us proper margins; @media print hides interactive UI; the layout
 * is single-column with print-safe typography.
 *
 * Linked from /app/reports/[id] via the "Download PDF" button which opens
 * this URL with `?autoprint=1` to trigger window.print() on load.
 */
export default async function ReportPrintView({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ autoprint?: string }>;
}) {
  const { id } = await params;
  const { autoprint } = await searchParams;
  const session = await getAppSession();
  assertActive(session);

  const supabase = await createAuthedServerClient();
  const { data } = await supabase
    .from("reports")
    .select("id, report_type, framework, generated_at, snapshot, ai_executive_summary")
    .eq("id", id)
    .eq("practice_id", session.membership.practice_id)
    .maybeSingle();
  if (!data) notFound();
  const r = data as ReportRow;
  const snap = r.snapshot ?? {};
  const generatedAt = new Date(r.generated_at).toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });

  return (
    <div className="report-print">
      <header className="report-header">
        <div className="brand">FORTIFY</div>
        <div className="meta">
          <p>{r.report_type.replace(/_/g, " ").toUpperCase()}{r.framework ? ` · ${r.framework}` : ""}</p>
          <p>{generatedAt}</p>
        </div>
      </header>

      <h1>{snap.practice_name ?? "Compliance report"}</h1>
      <p className="subtitle">Audit readiness snapshot &amp; executive summary</p>

      {/* Readiness grid */}
      {snap.readiness && snap.readiness.length > 0 && (
        <section>
          <h2>Per-framework posture</h2>
          <table className="readiness-table">
            <thead>
              <tr>
                <th>Framework</th>
                <th>Readiness</th>
                <th>Satisfied</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {snap.readiness.map((row) => (
                <tr key={row.framework_code}>
                  <td>{row.framework_code}</td>
                  <td className="num">{Math.round(Number(row.weighted_pct) || 0)}%</td>
                  <td className="num">{row.satisfied}</td>
                  <td className="num">{row.total}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {/* Key metrics */}
      <section>
        <h2>Key indicators</h2>
        <table className="indicators-table">
          <tbody>
            <tr>
              <td>Critical controls open</td>
              <td className="num">{snap.critical_open ?? 0}</td>
            </tr>
            <tr>
              <td>Drift alerts (last 30 days)</td>
              <td className="num">{snap.recent_drift_alerts_30d ?? 0}</td>
            </tr>
            <tr>
              <td>Vendors missing a current BAA</td>
              <td className="num">{snap.vendors_missing_baa ?? 0}</td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* Executive summary */}
      {r.ai_executive_summary && (
        <section className="summary">
          <h2>Executive summary</h2>
          <div className="summary-body">{r.ai_executive_summary}</div>
        </section>
      )}

      <footer className="report-footer">
        <p>
          Generated by Fortify. This document does not contain Protected Health Information
          (45 CFR §160.103). Fortify operates on compliance metadata only.
        </p>
        <p className="report-id">Report ID: {r.id}</p>
      </footer>

      {/* Auto-trigger browser print on load when ?autoprint=1 is set (default for the
          "Download PDF" button on the report page) so users get the print dialog
          immediately. They can also call window.print() manually from devtools. */}
      {autoprint !== "0" && (
        <script
          dangerouslySetInnerHTML={{
            __html: `window.addEventListener('load', () => setTimeout(() => window.print(), 250));`,
          }}
        />
      )}

      <style>{`
        @page { size: letter; margin: 0.75in; }
        html, body { background: white; color: #111; font-family: 'Times New Roman', Georgia, serif; }
        .report-print { max-width: 7.5in; margin: 0 auto; padding: 0.5in 0.25in; line-height: 1.55; }
        .report-header {
          display: flex; justify-content: space-between; align-items: baseline;
          border-bottom: 2px solid #111; padding-bottom: 10px; margin-bottom: 28px;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        }
        .brand { font-size: 12px; font-weight: 800; letter-spacing: 5px; }
        .meta { text-align: right; font-size: 10px; color: #555; }
        .meta p { margin: 0; }
        h1 { font-size: 32px; margin: 0 0 4px; letter-spacing: -0.01em; }
        .subtitle { color: #555; margin: 0 0 32px; font-style: italic; }
        h2 {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          font-size: 11px; text-transform: uppercase; letter-spacing: 2px;
          color: #555; margin: 28px 0 10px; border-bottom: 1px solid #ddd; padding-bottom: 6px;
        }
        table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 8px; }
        th, td { padding: 8px 6px; text-align: left; border-bottom: 1px solid #eee; }
        th { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #555; }
        td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
        .summary-body { font-size: 14px; line-height: 1.7; white-space: pre-wrap; }
        .report-footer {
          margin-top: 48px; padding-top: 14px; border-top: 1px solid #ddd;
          font-size: 10px; color: #666; font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        }
        .report-footer p { margin: 4px 0; }
        .report-id { font-family: 'Courier New', monospace; }

        @media print {
          .report-print { padding: 0; }
        }
      `}</style>
    </div>
  );
}
