-- 021_task_engine.sql
-- Promote remediation_tasks from a dormant table into the real assignment
-- system behind the virtual-compliance-officer surface. Adds direct control
-- linkage, a human-readable title, a task source (so we can distinguish
-- auto-generated control tasks from manual ones and policy-ack tasks), the
-- completing user, and a severity. A partial unique index prevents the task
-- generator from creating duplicate open auto-tasks for the same control.

alter table remediation_tasks
  add column if not exists control_id uuid references controls(id) on delete cascade,
  add column if not exists title text,
  add column if not exists source text not null default 'manual'
    check (source in ('auto_control','policy_ack','training','baa','screening','manual')),
  add column if not exists completed_by uuid references auth.users(id) on delete set null,
  add column if not exists severity text check (severity in ('critical','high','medium','low')),
  add column if not exists subject_ref text;   -- e.g. policy_id for policy_ack tasks

-- Prevent duplicate open auto-generated tasks per (practice, control, source).
-- Once a task is done/dismissed it leaves the index, so a fresh failure can
-- create a new task. COALESCE the nullable columns to empty-string sentinels
-- — Postgres treats NULLs as distinct, which would defeat a plain unique index
-- here (control_id is null for policy_ack, subject_ref is null for auto_control).
-- Uniqueness is per (practice, source, control, subject, assignee).
create unique index if not exists uniq_open_auto_task
  on remediation_tasks (
    practice_id,
    source,
    coalesce(control_id::text, ''),
    coalesce(subject_ref, ''),
    coalesce(assigned_to::text, '')
  )
  where status in ('open','in_progress','blocked');

create index if not exists idx_tasks_assignee
  on remediation_tasks (assigned_to, status);
create index if not exists idx_tasks_practice_status
  on remediation_tasks (practice_id, status);
create index if not exists idx_tasks_due
  on remediation_tasks (due_date) where status in ('open','in_progress','blocked');

-- RLS: members read their practice's tasks; assignees always read their own;
-- admins write. Service-role does generation.
alter table remediation_tasks enable row level security;

drop policy if exists tasks_member_read on remediation_tasks;
create policy tasks_member_read on remediation_tasks for select
  to authenticated
  using (
    user_is_practice_member(practice_id)
    or assigned_to = (select auth.uid())
  );

drop policy if exists tasks_admin_write on remediation_tasks;
create policy tasks_admin_write on remediation_tasks for all
  to authenticated
  using (user_is_practice_admin(practice_id))
  with check (user_is_practice_admin(practice_id));

-- Assignees can update their own task's status (mark in_progress/done) without
-- being an admin.
drop policy if exists tasks_assignee_update on remediation_tasks;
create policy tasks_assignee_update on remediation_tasks for update
  to authenticated
  using (assigned_to = (select auth.uid()))
  with check (assigned_to = (select auth.uid()));

grant select, insert, update on remediation_tasks to authenticated;
grant all on remediation_tasks to service_role;

comment on table remediation_tasks is
  'NO PHI. The task assignment system. auto_control + policy_ack rows are machine-generated by lib/compliance/tasks.ts; manual rows are admin-created.';
